title: "Felipe Estay's Academic Website"
description: "Sociologist and researcher focusing on system justification and perceptions of inequality."
permalink: ':title/'
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://felipestay.github.io" # The base hostname & protocol for your site
site-twitter: "" # If your site has a Twitter account, enter it here

# Author Settings
author: Felipe Estay # Add your name
author-img: Felipe-Estay.png # Add your photo
about-author: I am a sociologist pursuing a PhD in sociology at UC Chile. My research focuses on system justification, perceptions of inequality, exclusion pathways, homelessness, and social policy design. # Add description
social-twitter: https://twitter.com/Ngenpin # Add your Twitter handle
social-facebook: https://web.facebook.com/festaba1 # Add your Facebook handle
social-github: felipestay # Add your GitHub handle
social-linkedin: https://www.linkedin.com/in/felipe-estay-34433a243/ # Add your LinkedIn handle
social-email: fiestay@uc.cl # Add your Email address

# Disqus
disqus-identifier: "" # Add your Disqus identifier if you have one

# Tracker
analytics: "" # Google Analytics tracking ID

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
